device:
  platform: desktop
  name: Example Device
  fullscreen: false

# dummy_integration:

screen:
  poll_interval: 10   ##Amount of seconds between polling various device features

inkBoard:
  name: "Designer Test"
  date_format: "%A %d %B %Y" #"%A %d %B %Y"  #Date format datetime format string. Defaults to "%d-%m-%Y"
  time_format: "%H:%M" #Time format in datetime format string. Defaults to %H:%M
  integration_start_time: -1 #Time to wait for integrations to start, before moving on to running the dashboard. -1 means wait until they are all finished.

popups:
  - type: PopupMenu
    id: grid-popup
    title: "Popping up"
    menu_layout: grid-popup-layout

layouts:
  - type: custom:LabeledElements  ##If possible, maybe make the labels link to the documentation of said element
    id: small-elements
    outer_margins: 10
    inner_margins: 10
    rows: 4
    columns: 3
    elements:
      ##Buttons are similar to webpage buttons: some text and some other basic styling options
      - type: Button 
        text: Hello World!
        fit_text: true
        radius: h*0.1
        background_color: inkBoard-light
      ##Icons are similar to buttons, but instead of text they use icons
      ##Any mdi icon is valid as an icon, however image files can also be used (these will be styled to correspond to mdi icons)
      - type: Icon
        icon: mdi:shape
        background_shape: circle
        background_color: inkBoard-light
      ##Picture elements are similar to the Icon element, but do not do any styling or recoloring. Nor do they accept mdi:icons as value.
      - type: Picture
        picture: 1024px-Kingda_Ka.jpg
        background_shape: rounded_rectangle

      ##The AnalogueClock is an analogue clock that shows the time
      - type: AnalogueClock
        clock_fill_color: inkBoard
        tick_color: white
        hour_hand_color: white
        minute_hand_color: white
        outline_color: inkBoard

      ##The DigitalClock is, well, a digital clock
      - type: DigitalClock
        background_color: inkboard
        font_color: white

      ##A DateElement is similar to the DigitalClock, but is mainly meant to show e.g. dates.
      ##The date_format string must be a valid datetime format string for Python.
      - type: DateElement
        date_format: "%a %d %B"
        background_color: inkboard
        font_color: white

      ##The LineSlider is a Slider element has a position indicator that moves along the line
      - type: LineSlider
        id: example-lineslider
        minimum: 0
        maximum: 10
        color: inkBoard
        thumb_color: inkBoard-light
        end_points: [mdi:numeric-0-circle, mdi:numeric-10-circle]
        background_color: white
      ##The BoxSlider indicates it position by filling the box accordingly
      - type: BoxSlider
        inactive_color: inkBoard
        outline_color: inkBoard
        thumb_color: inkBoard
        active_color: inkBoard-light
        end_points: [mdi:numeric-0-circle, mdi:numeric-1-circle]
        background_color: white
      ##A TimerSlider can be used to show time progression. Both LineSlider and BoxSlider styles can be used, by setting style to line and box respectively. 
      - type: TimerSlider
        count: up
        style: box
        minimum: 0
        maximum: 45
        id: example-timerslider
        inactive_color: inkBoard
        outline_color: inkBoard
        thumb_color: inkBoard
        active_color: inkBoard-light
        background_color: white
        label_tap_action:
          action: element:toggle-timer
          element_id: example-timerslider

      ##A CheckBox is an icon that can be checked and unchecked. It also has an on_set action, that can be used to call functions when the state changes.
      - type: CheckBox
        checked_icon: mdi:checkbox-marked
        unchecked_icon: mdi:checkbox-blank
        icon_color: inkboard
        state_attributes:
          true:
            icon_color: inkBoard
          false:
            icon_color: gray
      ##A DropDown opens a popup from which an option can be selected.
      - type: DropDown
        options:
          - "inkBoard"
          - "green"
          - "yellow"
        opened_icon: mdi:eyedropper-variant
      ##A Counter displays a count, and can be increased and decreased. Using on_count, functions can be called when the value changes.
      - type: Counter
        minimum: 0
        maximum: 10
        on_count:
          ##Making elements interact with each other is possible like this.
          ##the action identifier element: makes it look for an element with the corresponding element_id, and use the function (provided the element has said function)
          action: element:set-position
          element_id: example-lineslider



  - type: GridLayout
    columns: 3
    rows: 1
    id: grid-popup-layout
    elements:
      - type: Button
        text: I'm in a popup layout!

  - type: GridLayout
    id: custom-elements
    columns: 3
    rows: 1
    row_size: "h*0.5"
    column_size: ["w*0.4", "w*0.15", w*0.4]
    outer_margins: [h*0.25, 25]
    inner_margins: 10
    elements:
      - type: Button
        font: DancingScript-Bold.ttf
        text: I can write in a custom font!
        background_color: inkboard-light
      - type: Icon
        icon: speaker-outline.png
        icon_color: white
        background_color: inkboard
        background_shape: circle
      - type: Picture
        picture: 1024px-Kingda_Ka.jpg
        background_shape: rounded_rectangle


main_tabs:
  ##Add some defaults in the parser here for markup (i.e. margins etc.)
  foreground_color: inkboard-light
  element_properties:
    navigation:
      inactive_properties:
        background_color: None
        radius: 5
        element_properties:
          name: 
            font_color: gray
      active_properties:
        background_color: [255, 255, 255, 200]
        element_properties:
          name: 
            font_color: active
  tabs:
    - element: small-elements
      name: Breakfast
      icon: mdi:bread-slice
    - element: custom-elements
      name: "Elements"

##Don't forget to include the statusbar