name: Build distribution on push

on: 
    push:
    workflow_call:

jobs:
    build:
        strategy:
          matrix:
            python-version: ['3.9', '3.10']
        name: Python ${{ matrix.python-version }}, Build distribution 📦
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
                python-version:  ${{ matrix.python-version }}
        - name: Install pypa/build
          run: >-
            python3 -m
            pip install
            build
            --user
        - name: Build a binary wheel and a source tarball
          run: python3 -m build
        - name: Store the distribution packages
          if: ${{ matrix.python-version == '3.9' }}
          id: storedist
          uses: actions/upload-artifact@v4
          with:
            name: python-package-distributions
            path: dist/
        - name: Generate index file
          if: ${{ matrix.python-version == '3.9' }}
          run: python "scripts/create_index.py"