name: Create the index.json file

on: 
    pull_request:
        types:
          - closed
        branches:
          - 'main'
          - 'dev'
    workflow_dispatch:

jobs:
    create_index:
        name: Create inkBoard index file
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            # Semantic version range syntax or exact version of a Python version
            python-version: '3.9'
        - name: Install artifact
          run: python3 -m pip install -e '.'
        - name: Generate index file
          run: python "scripts/create_index.py"
        - name: Store the index file
          id: storedist
          uses: actions/upload-artifact@v4
          with:
            name: index-file
            path: index.json
        - name: update file and push to remote
          run: |
              echo "Test push commit to the remote in the workflow" >> test.txt
    
              git config --global user.name "github-actions[bot]"
              git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
              git add index.json
              git commit -m "Update index.json"
              git fetch origin dev
              git push origin dev

        