name: Create the index.json file

on: 
    pull_request:
        types:
          - closed
        branches:
          - 'main'
          - 'dev'
    workflow_dispatch:

permissions:                    # Global permissions configuration starts here
  contents: write               # 'read' access to repository contents

jobs:
    create_index:
        name: Create inkBoard index file
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:  
            ref: dev
            path: designer
        - uses: actions/checkout@v4
          with:  
            repository: Slalamander/inkBoard
            ref: dev
            path: inkBoard
        - uses: actions/checkout@v4
          with:  
            repository: Slalamander/PythonScreenStackManager
            ref: dev
            path: pssm
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            # Semantic version range syntax or exact version of a Python version
            python-version: '3.9'
        - name: Install editable inkBoard packages
          run: python3 -m pip install -e './designer' './inkBoard' './pssm' 
        - name: Generate index file
          run: python "designer/scripts/create_index.py"
        - name: Store the index file
          id: storedist
          uses: actions/upload-artifact@v4
          with:
            name: index-file
            path: index.json
        - name: update file and push to remote
          run: |
              echo "Pushing updated index.json file"
    
              cd ./designer

              git config --global user.name "github-actions[bot]"
              git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
              git add ../index.json
              git commit -m "Update index.json"
              git fetch origin dev
              git push origin dev

        